# Generated by Django 3.0.5 on 2020-04-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['posted_date']},
        ),
    ]
