# Generated by Django 3.0.5 on 2020-04-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsupportmessage',
            name='sub_category',
            field=models.CharField(choices=[('Sign in Problems', 'Sign in Problems'), ('Escrow Service', 'Escrow Service'), ('Report a User', 'Report a User'), ('Security Issues', 'Security Issues'), ('Registration Issues', 'Registration Issues'), ('Forum Issues', 'Forum Issues'), ('Miscellaneous', 'miscellaneous')], max_length=100),
        ),
    ]
