# Generated by Django 3.0.5 on 2020-04-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='dir_image',
            field=models.ImageField(blank=True, null=True, upload_to='directories/images/'),
        ),
    ]
