# Generated by Django 3.0.5 on 2020-04-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20200415_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='dir_image',
            field=models.ImageField(blank=True, default='directories/images/default-image.jpg', null=True, upload_to='directories/images/'),
        ),
    ]
