# Generated by Django 3.0.5 on 2020-04-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20200415_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='section_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
