# Generated by Django 3.0.5 on 2020-04-15 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20200415_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_active_post',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='number_of_posts',
            field=models.IntegerField(default=0),
        ),
    ]
