# Generated by Django 3.0.5 on 2020-04-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_auto_20200415_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-posted_date']},
        ),
    ]
