# Generated by Django 3.0.5 on 2020-04-22 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='default', max_length=120, unique=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('abandoned', 'abandoned'), ('completed', 'completed')], default='started', max_length=120)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
